sequenceDiagram
    participant browser
    participant server

    Note right of browser: User writes a note and clicks Save

    browser->>server: POST /exampleapp/new_note
    activate server

    Note right of browser: The browser sends the data to the server
    
    server-->>browser: HTTP 302 Redirect
    deactivate server

    browser->>server: GET /exampleapp/notes
    activate server
    server-->>browser: HTML Document
    deactivate server

    browser->>server: GET /exampleapp/main.css
    activate server
    server-->>browser: The CSS File
    deactivate server

    browser->>server: GET /exampleapp/main.js
    activate server
    server-->>browser: The JavaScript File
    deactivate server

    Note right of browser: Browser executes the JavaScript code

    browser->>server: GET /exampleapp/data.json
    activate server
    server-->>browser: JSON data containing the new note
    deactivate server

    Note right of browser: JavaScript renders the notes, including the new note!